on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Remove unused file
        run: rm -f dist/pagefind/pagefind-(highlight|modular|ui)*

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kodot-app
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
